# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User Home Page.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

#importing all related gui files
from assign_VIP_dialog import *
from send_compliment_dialog import *
from send_complaint_dialog import *
from meet_up_poll_dialog import *
from more_group_profiles import *
from more_user_profiles import *
from kick_out_member_poll_dialog import *
from group_closing_poll import *
from invite_dialog import *
from reference_dialog import *

from TeamMe.system import system

class Ui_userHomeMain(object):
     #a function to hide tabs based on user type
    def hideTab(self):
        #If current user is an OU, need to hide tab 4 and 5 (admin tabs)
        if isinstance(system.current_user,OU):
            self.tabWidget.removeTab(4)
            self.tabWidget.removeTab(5)
        #if current user is a vip, need to hide tab 4(SU)
        elif isinstance(system.current_user,VIP):
            self.tabWidget.removeTab(4)
        #if current user is a SU, need to hide tab 5(VIP)
        elif isinstance(system.current_user,SU):
            self.tabWidget.removeTab(5)

    def referClicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ReferenceDialog()
        self.ui.setupUi(self.window)
        self.window.show()

    #assigning a vip for group eval
    def VipAssigned(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def complimentClicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_compliment()
        self.ui.setupUi(self.window)
        self.window.show()

    def complaintClicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_complaint()
        self.ui.setupUi(self.window)
        self.window.show()

    def meetingPoll(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_meetup()
        self.ui.setupUi(self.window)
        self.window.show()

    def seeMoreGroups(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_moreGroups()
        self.ui.setupUi(self.window)
        self.window.show()

    def seeMoreUsers(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_moreUsers()
        self.ui.setupUi(self.window)
        self.window.show()

    def kickAMember(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_kickMember()
        self.ui.setupUi(self.window)
        self.window.show()

    def closeGroup(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_closingGroup()
        self.ui.setupUi(self.window)
        self.window.show()

    def invited(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_inviteDialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def selectAllInv(self):
        if self.checkBox.isChecked() != True:
            self.checkBox.click()
        if self.checkBox_2.isChecked() != True:
            self.checkBox_2.click()
        if self.checkBox_3.isChecked() != True:
            self.checkBox_3.click()

    def deselectAllInv(self):
        if self.checkBox.isChecked() == True:
            self.checkBox.click()
        if self.checkBox_2.isChecked() == True:
            self.checkBox_2.click()
        if self.checkBox_3.isChecked() == True:
            self.checkBox_3.click()

    def selectAllMsg(self):
        if self.checkBox_4.isChecked() != True:
            self.checkBox_4.click()
        if self.checkBox_5.isChecked() != True:
            self.checkBox_5.click()

    def deselectAllMsg(self):
        if self.checkBox_4.isChecked() == True:
            self.checkBox_4.click()
        if self.checkBox_5.isChecked() == True:
            self.checkBox_5.click()

    def selectAllAcc(self):
        if self.checkBox_6.isChecked() != True:
            self.checkBox_6.click()
        if self.checkBox_8.isChecked() != True:
            self.checkBox_8.click()


    def deselectAllAcc(self):
        if self.checkBox_6.isChecked() == True:
            self.checkBox_6.click()
        if self.checkBox_8.isChecked() == True:
            self.checkBox_8.click()

    def selectAllEval(self):
        if self.checkBox_15.isChecked() != True:
            self.checkBox_15.click()
        if self.checkBox_16.isChecked() != True:
            self.checkBox_16.click()
        if self.checkBox_17.isChecked() != True:
            self.checkBox_17.click()
        if self.checkBox_31.isChecked() != True:
            self.checkBox_31.click()

    def deselectAllEval(self):
        if self.checkBox_15.isChecked() == True:
            self.checkBox_15.click()
        if self.checkBox_16.isChecked() == True:
            self.checkBox_16.click()
        if self.checkBox_17.isChecked() == True:
            self.checkBox_17.click()
        if self.checkBox_31.isChecked() == True:
            self.checkBox_31.click()

    def profileEdited(self):
        system.current_user.intro = self.plainTextEdit.toPlainText()
        system.current_user.languages = self.plainTextEdit_3.toPlainText()
        system.current_user.affiliatedGroups = self.plainTextEdit_2.toPlainText()


    def setupUi(self, userHomeMain):

        #changes
        self.oldWindow = userHomeMain


        userHomeMain.setObjectName("userHomeMain")
        userHomeMain.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(userHomeMain)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 771, 561))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.pushButton_3 = QtWidgets.QPushButton(self.homeTab)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 200, 100, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_12 = QtWidgets.QLabel(self.homeTab)
        self.label_12.setGeometry(QtCore.QRect(46, 39, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.layoutWidget_2 = QtWidgets.QWidget(self.homeTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 159, 128, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.label_8 = QtWidgets.QLabel(self.homeTab)
        self.label_8.setGeometry(QtCore.QRect(90, 99, 127, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.homeTab)
        self.label_10.setGeometry(QtCore.QRect(120, 129, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.homeTab)
        self.label_4.setGeometry(QtCore.QRect(41, 130, 78, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.homeTab)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 80, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.homeTab)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.homeTab)
        self.plainTextEdit.setGeometry(QtCore.QRect(310, 60, 341, 211))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.homeTab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(310, 320, 341, 191))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.homeTab)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(30, 320, 241, 191))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_7 = QtWidgets.QLabel(self.homeTab)
        self.label_7.setGeometry(QtCore.QRect(311, 289, 152, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.homeTab)
        self.label_9.setGeometry(QtCore.QRect(31, 289, 221, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.homeTab, "")
        self.browserTab = QtWidgets.QWidget()
        self.browserTab.setObjectName("browserTab")
        self.topUserLabel = QtWidgets.QLabel(self.browserTab)
        self.topUserLabel.setGeometry(QtCore.QRect(420, 21, 226, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.topUserLabel.setFont(font)
        self.topUserLabel.setObjectName("topUserLabel")
        self.group1_textBrowser = QtWidgets.QTextBrowser(self.browserTab)
        self.group1_textBrowser.setGeometry(QtCore.QRect(20, 110, 331, 101))
        self.group1_textBrowser.setObjectName("group1_textBrowser")
        self.user1_textBrowser = QtWidgets.QTextBrowser(self.browserTab)
        self.user1_textBrowser.setGeometry(QtCore.QRect(420, 110, 331, 101))
        self.user1_textBrowser.setObjectName("user1_textBrowser")
        self.label = QtWidgets.QLabel(self.browserTab)
        self.label.setGeometry(QtCore.QRect(21, 21, 245, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.user2_textBrowser = QtWidgets.QTextBrowser(self.browserTab)
        self.user2_textBrowser.setGeometry(QtCore.QRect(420, 260, 331, 101))
        self.user2_textBrowser.setObjectName("user2_textBrowser")
        self.group2_textBrowser = QtWidgets.QTextBrowser(self.browserTab)
        self.group2_textBrowser.setGeometry(QtCore.QRect(20, 260, 331, 101))
        self.group2_textBrowser.setObjectName("group2_textBrowser")
        self.user3_textBrowser = QtWidgets.QTextBrowser(self.browserTab)
        self.user3_textBrowser.setGeometry(QtCore.QRect(420, 410, 331, 101))
        self.user3_textBrowser.setObjectName("user3_textBrowser")
        self.group3_textBrowser = QtWidgets.QTextBrowser(self.browserTab)
        self.group3_textBrowser.setGeometry(QtCore.QRect(20, 410, 331, 101))
        self.group3_textBrowser.setObjectName("group3_textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.browserTab)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 60, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_26 = QtWidgets.QPushButton(self.browserTab)
        self.pushButton_26.setGeometry(QtCore.QRect(660, 60, 93, 28))
        self.pushButton_26.setObjectName("pushButton_26")
        self.group1_button = QtWidgets.QPushButton(self.browserTab)
        self.group1_button.setGeometry(QtCore.QRect(10, 80, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.group1_button.setFont(font)
        self.group1_button.setFlat(True)
        self.group1_button.setObjectName("group1_button")
        self.group2_button = QtWidgets.QPushButton(self.browserTab)
        self.group2_button.setGeometry(QtCore.QRect(10, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.group2_button.setFont(font)
        self.group2_button.setFlat(True)
        self.group2_button.setObjectName("group2_button")
        self.group3_button = QtWidgets.QPushButton(self.browserTab)
        self.group3_button.setGeometry(QtCore.QRect(10, 380, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.group3_button.setFont(font)
        self.group3_button.setFlat(True)
        self.group3_button.setObjectName("group3_button")
        self.user2_button = QtWidgets.QPushButton(self.browserTab)
        self.user2_button.setGeometry(QtCore.QRect(410, 230, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.user2_button.setFont(font)
        self.user2_button.setFlat(True)
        self.user2_button.setObjectName("user2_button")
        self.user3_button = QtWidgets.QPushButton(self.browserTab)
        self.user3_button.setGeometry(QtCore.QRect(410, 380, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.user3_button.setFont(font)
        self.user3_button.setFlat(True)
        self.user3_button.setObjectName("user3_button")
        self.user1_button = QtWidgets.QPushButton(self.browserTab)
        self.user1_button.setGeometry(QtCore.QRect(410, 80, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.user1_button.setFont(font)
        self.user1_button.setFlat(True)
        self.user1_button.setObjectName("user1_button")
        self.tabWidget.addTab(self.browserTab, "")
        self.inboxTab = QtWidgets.QWidget()
        self.inboxTab.setObjectName("inboxTab")
        self.label_5 = QtWidgets.QLabel(self.inboxTab)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.inboxTab)
        self.label_11.setGeometry(QtCore.QRect(400, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.checkBox = QtWidgets.QCheckBox(self.inboxTab)
        self.checkBox.setGeometry(QtCore.QRect(20, 110, 111, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.inboxTab)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 220, 141, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.inboxTab)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 330, 151, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.inboxTab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 140, 341, 71))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.inboxTab)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 250, 341, 71))
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.inboxTab)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 360, 341, 71))
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton.setGeometry(QtCore.QRect(20, 450, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 481, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setDefault(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.line = QtWidgets.QFrame(self.inboxTab)
        self.line.setGeometry(QtCore.QRect(30, 60, 341, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_5 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 100, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setDefault(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 70, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setDefault(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.line_2 = QtWidgets.QFrame(self.inboxTab)
        self.line_2.setGeometry(QtCore.QRect(400, 60, 341, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.inboxTab)
        self.textBrowser_4.setGeometry(QtCore.QRect(400, 250, 341, 71))
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.checkBox_4 = QtWidgets.QCheckBox(self.inboxTab)
        self.checkBox_4.setGeometry(QtCore.QRect(400, 220, 151, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.inboxTab)
        self.textBrowser_5.setGeometry(QtCore.QRect(400, 140, 341, 71))
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.checkBox_5 = QtWidgets.QCheckBox(self.inboxTab)
        self.checkBox_5.setGeometry(QtCore.QRect(400, 110, 181, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_7.setGeometry(QtCore.QRect(650, 70, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_8.setGeometry(QtCore.QRect(650, 100, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_10.setGeometry(QtCore.QRect(400, 449, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setDefault(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_9.setGeometry(QtCore.QRect(400, 480, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setDefault(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_27 = QtWidgets.QPushButton(self.inboxTab)
        self.pushButton_27.setGeometry(QtCore.QRect(650, 10, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setDefault(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.tabWidget.addTab(self.inboxTab, "")
        self.groupManagementTab = QtWidgets.QWidget()
        self.groupManagementTab.setObjectName("groupManagementTab")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_15.setGeometry(QtCore.QRect(250, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setDefault(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupManagementTab)
        self.listWidget_6.setGeometry(QtCore.QRect(20, 60, 341, 201))
        self.listWidget_6.setObjectName("listWidget_6")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        self.label_14 = QtWidgets.QLabel(self.groupManagementTab)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 233, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 270, 111, 31))
        self.pushButton_16.setDefault(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.line_4 = QtWidgets.QFrame(self.groupManagementTab)
        self.line_4.setGeometry(QtCore.QRect(20, 40, 341, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_15 = QtWidgets.QLabel(self.groupManagementTab)
        self.label_15.setGeometry(QtCore.QRect(30, 300, 233, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupManagementTab)
        self.label_16.setGeometry(QtCore.QRect(410, 10, 233, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.line_5 = QtWidgets.QFrame(self.groupManagementTab)
        self.line_5.setGeometry(QtCore.QRect(410, 40, 341, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_17.setGeometry(QtCore.QRect(410, 60, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setDefault(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_18.setGeometry(QtCore.QRect(410, 100, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setDefault(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_19.setGeometry(QtCore.QRect(410, 140, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setDefault(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_20.setGeometry(QtCore.QRect(410, 180, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setDefault(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupManagementTab)
        self.pushButton_21.setGeometry(QtCore.QRect(410, 220, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setDefault(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_17 = QtWidgets.QLabel(self.groupManagementTab)
        self.label_17.setGeometry(QtCore.QRect(20, 340, 233, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.line_6 = QtWidgets.QFrame(self.groupManagementTab)
        self.line_6.setGeometry(QtCore.QRect(20, 370, 341, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_18 = QtWidgets.QLabel(self.groupManagementTab)
        self.label_18.setGeometry(QtCore.QRect(20, 390, 271, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupManagementTab)
        self.label_19.setGeometry(QtCore.QRect(20, 420, 271, 21))
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.groupManagementTab, "")
        self.adminSUTab = QtWidgets.QWidget()
        self.adminSUTab.setObjectName("adminSUTab")
        self.line_3 = QtWidgets.QFrame(self.adminSUTab)
        self.line_3.setGeometry(QtCore.QRect(10, 50, 341, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_13 = QtWidgets.QLabel(self.adminSUTab)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.adminSUTab)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 60, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setDefault(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.adminSUTab)
        self.pushButton_12.setGeometry(QtCore.QRect(110, 260, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setDefault(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.adminSUTab)
        self.pushButton_13.setGeometry(QtCore.QRect(260, 60, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setDefault(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.adminSUTab)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 259, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setDefault(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.scrollArea = QtWidgets.QScrollArea(self.adminSUTab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 90, 341, 161))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_7.setGeometry(QtCore.QRect(0, 30, 321, 41))
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 90, 301, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_8.setGeometry(QtCore.QRect(0, 0, 301, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_9.setGeometry(QtCore.QRect(0, 110, 321, 41))
        self.textBrowser_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_8.setGeometry(QtCore.QRect(0, 250, 321, 41))
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_9.setGeometry(QtCore.QRect(0, 230, 301, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line_7 = QtWidgets.QFrame(self.adminSUTab)
        self.line_7.setGeometry(QtCore.QRect(400, 50, 341, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_20 = QtWidgets.QLabel(self.adminSUTab)
        self.label_20.setGeometry(QtCore.QRect(400, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.adminSUTab)
        self.label_21.setGeometry(QtCore.QRect(400, 300, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.line_8 = QtWidgets.QFrame(self.adminSUTab)
        self.line_8.setGeometry(QtCore.QRect(400, 330, 341, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.adminSUTab)
        self.scrollArea_2.setGeometry(QtCore.QRect(400, 70, 341, 161))
        self.scrollArea_2.setAutoFillBackground(False)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 318, 159))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_10.setGeometry(QtCore.QRect(0, 30, 321, 41))
        self.textBrowser_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_7.setGeometry(QtCore.QRect(0, 80, 301, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_10.setGeometry(QtCore.QRect(0, 10, 301, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_11.setGeometry(QtCore.QRect(0, 100, 321, 41))
        self.textBrowser_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser_12.setGeometry(QtCore.QRect(0, 250, 321, 41))
        self.textBrowser_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_11.setGeometry(QtCore.QRect(0, 230, 301, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.adminSUTab)
        self.scrollArea_3.setGeometry(QtCore.QRect(400, 350, 341, 161))
        self.scrollArea_3.setAutoFillBackground(False)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 318, 159))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.textBrowser_13.setGeometry(QtCore.QRect(0, 40, 321, 41))
        self.textBrowser_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.textBrowser_14.setGeometry(QtCore.QRect(0, 130, 321, 41))
        self.textBrowser_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.textBrowser_15.setGeometry(QtCore.QRect(0, 250, 321, 41))
        self.textBrowser_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.checkBox_14.setGeometry(QtCore.QRect(0, 230, 301, 20))
        self.checkBox_14.setObjectName("checkBox_14")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_23.setGeometry(QtCore.QRect(0, 10, 181, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_24.setGeometry(QtCore.QRect(0, 100, 181, 21))
        self.label_24.setObjectName("label_24")
        self.pushButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_22.setGeometry(QtCore.QRect(220, 10, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setAutoDefault(True)
        self.pushButton_22.setDefault(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_23.setGeometry(QtCore.QRect(220, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setAutoDefault(True)
        self.pushButton_23.setDefault(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.pushButton_24 = QtWidgets.QPushButton(self.adminSUTab)
        self.pushButton_24.setGeometry(QtCore.QRect(400, 239, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setDefault(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.adminSUTab)
        self.pushButton_25.setGeometry(QtCore.QRect(400, 270, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setDefault(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.line_34 = QtWidgets.QFrame(self.adminSUTab)
        self.line_34.setGeometry(QtCore.QRect(10, 330, 341, 16))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.label_83 = QtWidgets.QLabel(self.adminSUTab)
        self.label_83.setGeometry(QtCore.QRect(10, 300, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.scrollArea_15 = QtWidgets.QScrollArea(self.adminSUTab)
        self.scrollArea_15.setGeometry(QtCore.QRect(10, 350, 341, 161))
        self.scrollArea_15.setAutoFillBackground(False)
        self.scrollArea_15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_15.setWidgetResizable(True)
        self.scrollArea_15.setObjectName("scrollArea_15")
        self.scrollAreaWidgetContents_15 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_15.setGeometry(QtCore.QRect(0, 0, 318, 159))
        self.scrollAreaWidgetContents_15.setObjectName("scrollAreaWidgetContents_15")
        self.textBrowser_62 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_15)
        self.textBrowser_62.setGeometry(QtCore.QRect(0, 40, 321, 41))
        self.textBrowser_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_62.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_62.setObjectName("textBrowser_62")
        self.textBrowser_63 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_15)
        self.textBrowser_63.setGeometry(QtCore.QRect(0, 130, 321, 41))
        self.textBrowser_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_63.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_63.setObjectName("textBrowser_63")
        self.textBrowser_64 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_15)
        self.textBrowser_64.setGeometry(QtCore.QRect(0, 250, 321, 41))
        self.textBrowser_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_64.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_64.setObjectName("textBrowser_64")
        self.checkBox_48 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_15)
        self.checkBox_48.setGeometry(QtCore.QRect(0, 230, 301, 20))
        self.checkBox_48.setObjectName("checkBox_48")
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents_15)
        self.label_84.setGeometry(QtCore.QRect(0, 10, 181, 21))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents_15)
        self.label_85.setGeometry(QtCore.QRect(0, 100, 181, 21))
        self.label_85.setObjectName("label_85")
        self.pushButton_95 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_15)
        self.pushButton_95.setGeometry(QtCore.QRect(220, 10, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_95.setFont(font)
        self.pushButton_95.setAutoDefault(True)
        self.pushButton_95.setDefault(False)
        self.pushButton_95.setObjectName("pushButton_95")
        self.pushButton_96 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_15)
        self.pushButton_96.setGeometry(QtCore.QRect(220, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_96.setFont(font)
        self.pushButton_96.setAutoDefault(True)
        self.pushButton_96.setDefault(False)
        self.pushButton_96.setObjectName("pushButton_96")
        self.scrollArea_15.setWidget(self.scrollAreaWidgetContents_15)
        self.tabWidget.addTab(self.adminSUTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_4.setGeometry(QtCore.QRect(30, 121, 341, 311))
        self.scrollArea_4.setAutoFillBackground(False)
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 318, 309))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_4)
        self.textBrowser_16.setGeometry(QtCore.QRect(0, 40, 321, 41))
        self.textBrowser_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_15.setGeometry(QtCore.QRect(0, 90, 301, 20))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_16.setGeometry(QtCore.QRect(0, 10, 301, 20))
        self.checkBox_16.setObjectName("checkBox_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_4)
        self.textBrowser_17.setGeometry(QtCore.QRect(0, 110, 321, 41))
        self.textBrowser_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_4)
        self.textBrowser_18.setGeometry(QtCore.QRect(0, 180, 321, 41))
        self.textBrowser_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_17.setGeometry(QtCore.QRect(0, 160, 301, 20))
        self.checkBox_17.setObjectName("checkBox_17")
        self.textBrowser_35 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_4)
        self.textBrowser_35.setGeometry(QtCore.QRect(0, 260, 321, 41))
        self.textBrowser_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_35.setObjectName("textBrowser_35")
        self.checkBox_31 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.checkBox_31.setGeometry(QtCore.QRect(0, 240, 301, 20))
        self.checkBox_31.setObjectName("checkBox_31")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(30, 50, 341, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(30, 20, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.pushButton_56 = QtWidgets.QPushButton(self.tab)
        self.pushButton_56.setGeometry(QtCore.QRect(280, 90, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setDefault(True)
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.tab)
        self.pushButton_57.setGeometry(QtCore.QRect(280, 60, 93, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setDefault(True)
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_55 = QtWidgets.QPushButton(self.tab)
        self.pushButton_55.setGeometry(QtCore.QRect(30, 450, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setDefault(True)
        self.pushButton_55.setObjectName("pushButton_55")
        self.line_21 = QtWidgets.QFrame(self.tab)
        self.line_21.setGeometry(QtCore.QRect(410, 50, 341, 16))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.label_49 = QtWidgets.QLabel(self.tab)
        self.label_49.setGeometry(QtCore.QRect(410, 20, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.scrollArea_9 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_9.setGeometry(QtCore.QRect(410, 80, 341, 251))
        self.scrollArea_9.setAutoFillBackground(False)
        self.scrollArea_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 318, 249))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.textBrowser_36 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_9)
        self.textBrowser_36.setGeometry(QtCore.QRect(0, 40, 321, 41))
        self.textBrowser_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_36.setObjectName("textBrowser_36")
        self.textBrowser_37 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_9)
        self.textBrowser_37.setGeometry(QtCore.QRect(0, 130, 321, 41))
        self.textBrowser_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_37.setObjectName("textBrowser_37")
        self.textBrowser_38 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_9)
        self.textBrowser_38.setGeometry(QtCore.QRect(0, 250, 321, 41))
        self.textBrowser_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_38.setObjectName("textBrowser_38")
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        self.label_50.setGeometry(QtCore.QRect(0, 10, 181, 21))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        self.label_51.setGeometry(QtCore.QRect(0, 100, 181, 21))
        self.label_51.setObjectName("label_51")
        self.pushButton_58 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_58.setGeometry(QtCore.QRect(220, 10, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setAutoDefault(True)
        self.pushButton_58.setDefault(False)
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_59.setGeometry(QtCore.QRect(220, 100, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setAutoDefault(True)
        self.pushButton_59.setDefault(False)
        self.pushButton_59.setObjectName("pushButton_59")
        self.textBrowser_39 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_9)
        self.textBrowser_39.setGeometry(QtCore.QRect(0, 220, 321, 41))
        self.textBrowser_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_39.setObjectName("textBrowser_39")
        self.pushButton_60 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_60.setGeometry(QtCore.QRect(220, 190, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setAutoDefault(True)
        self.pushButton_60.setDefault(False)
        self.pushButton_60.setObjectName("pushButton_60")
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_9)
        self.label_52.setGeometry(QtCore.QRect(0, 190, 181, 21))
        self.label_52.setObjectName("label_52")
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_9)
        self.label_81 = QtWidgets.QLabel(self.tab)
        self.label_81.setGeometry(QtCore.QRect(410, 370, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.line_33 = QtWidgets.QFrame(self.tab)
        self.line_33.setGeometry(QtCore.QRect(410, 400, 341, 16))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.label_82 = QtWidgets.QLabel(self.tab)
        self.label_82.setGeometry(QtCore.QRect(410, 420, 201, 21))
        self.label_82.setObjectName("label_82")
        self.pushButton_94 = QtWidgets.QPushButton(self.tab)
        self.pushButton_94.setGeometry(QtCore.QRect(410, 460, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_94.setFont(font)
        self.pushButton_94.setAutoDefault(False)
        self.pushButton_94.setDefault(True)
        self.pushButton_94.setObjectName("pushButton_94")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setGeometry(QtCore.QRect(20, 50, 341, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(20, 260, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.line_22 = QtWidgets.QFrame(self.tab_2)
        self.line_22.setGeometry(QtCore.QRect(20, 290, 341, 16))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.tabWidget.addTab(self.tab_2, "")
        userHomeMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(userHomeMain)
        self.statusbar.setObjectName("statusbar")
        userHomeMain.setStatusBar(self.statusbar)

        self.retranslateUi(userHomeMain)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(userHomeMain)

                        #changes
        self.pushButton_27.clicked.connect(self.referClicked)
        self.pushButton_22.clicked.connect(self.VipAssigned)
        self.pushButton_23.clicked.connect(self.VipAssigned)
        self.pushButton_20.clicked.connect(self.complimentClicked)
        self.pushButton_19.clicked.connect(self.complaintClicked)
        self.pushButton_17.clicked.connect(self.meetingPoll)
        self.pushButton_2.clicked.connect(self.seeMoreGroups)
        self.pushButton_26.clicked.connect(self.seeMoreUsers)
        self.pushButton_21.clicked.connect(self.kickAMember)
        self.pushButton_18.clicked.connect(self.closeGroup)
        self.pushButton_16.clicked.connect(self.invited)
        self.pushButton_6.clicked.connect(self.selectAllInv)
        self.pushButton_5.clicked.connect(self.deselectAllInv)
        self.pushButton_7.clicked.connect(self.selectAllMsg)
        self.pushButton_8.clicked.connect(self.deselectAllMsg)
        self.pushButton_11.clicked.connect(self.selectAllAcc)
        self.pushButton_13.clicked.connect(self.deselectAllAcc)
        self.pushButton_57.clicked.connect(self.selectAllEval)
        self.pushButton_56.clicked.connect(self.deselectAllEval)
        self.pushButton_3.clicked.connect(self.profileEdited)


    def retranslateUi(self, userHomeMain):
        _translate = QtCore.QCoreApplication.translate
        userHomeMain.setWindowTitle(_translate("userHomeMain", "User Home Page"))
        self.pushButton_3.setText(_translate("userHomeMain", "Save Changes"))
        self.label_12.setText(_translate("userHomeMain", system.current_user.username))
        self.label_6.setText(_translate("userHomeMain", "Reputation"))
        self.label_26.setText(_translate("userHomeMain", str(system.current_user.score)))
        self.label_8.setText(_translate("userHomeMain", system.current_user.email))
        self.label_10.setText(_translate("userHomeMain", system.current_user.interests))
        self.label_4.setText(_translate("userHomeMain", "Interests: "))
        self.label_2.setText(_translate("userHomeMain", "About Me"))
        self.label_3.setText(_translate("userHomeMain", "Email:"))
        self.plainTextEdit.setPlainText(system.current_user.intro)
        self.plainTextEdit_2.setPlainText(system.current_user.affiliatedGroups)
        self.plainTextEdit_3.setPlainText(system.current_user.languages)
        self.label_7.setText(_translate("userHomeMain", "Groups Affiliation"))
        self.label_9.setText(_translate("userHomeMain", "Programming Languages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("userHomeMain", "Home"))
        self.topUserLabel.setText(_translate("userHomeMain", "Top 3 User Profiles"))
        self.label.setText(_translate("userHomeMain", "Top 3 Group Profiles"))
        self.pushButton_2.setText(_translate("userHomeMain", "more"))
        self.pushButton_26.setText(_translate("userHomeMain", "more"))
        self.group1_button.setText(_translate("userHomeMain", "Group 1"))
        self.group2_button.setText(_translate("userHomeMain", "Group 2"))
        self.group3_button.setText(_translate("userHomeMain", "Group 3"))
        self.user2_button.setText(_translate("userHomeMain", "User 2"))
        self.user3_button.setText(_translate("userHomeMain", "User 3"))
        self.user1_button.setText(_translate("userHomeMain", "User 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browserTab), _translate("userHomeMain", "Browser"))
        self.label_5.setText(_translate("userHomeMain", "Invitations"))
        self.label_11.setText(_translate("userHomeMain", "Other messages"))
        self.checkBox.setText(_translate("userHomeMain", "Invitation A"))
        self.checkBox_2.setText(_translate("userHomeMain", "Invitation B"))
        self.checkBox_3.setText(_translate("userHomeMain", "Invitation C"))
        self.textBrowser.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Invitation message: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Details include potential projects, other group members, etc.</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Invitation message: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Details include potential projects, other group members, etc.</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Invitation message: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Details include potential projects, other group members, etc.</p></body></html>"))
        self.pushButton.setText(_translate("userHomeMain", " Accept"))
        self.pushButton_4.setText(_translate("userHomeMain", "Reject"))
        self.pushButton_5.setText(_translate("userHomeMain", "Deselect All"))
        self.pushButton_6.setText(_translate("userHomeMain", "Select All"))
        self.textBrowser_4.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Member to be kicked out and reason(s).</p></body></html>"))
        self.checkBox_4.setText(_translate("userHomeMain", "Kick Out Member Poll"))
        self.textBrowser_5.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Meeting time and date</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkBox_5.setText(_translate("userHomeMain", "Meeting Poll A"))
        self.pushButton_7.setText(_translate("userHomeMain", "Select All"))
        self.pushButton_8.setText(_translate("userHomeMain", "Deselect All"))
        self.pushButton_10.setText(_translate("userHomeMain", " Accept"))
        self.pushButton_9.setText(_translate("userHomeMain", "Reject"))
        self.pushButton_27.setText(_translate("userHomeMain", "Refer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inboxTab), _translate("userHomeMain", "Inbox"))
        self.pushButton_15.setText(_translate("userHomeMain", "Edit Group Page"))
        __sortingEnabled = self.listWidget_6.isSortingEnabled()
        self.listWidget_6.setSortingEnabled(False)
        item = self.listWidget_6.item(0)
        item.setText(_translate("userHomeMain", "User Profile A"))
        item = self.listWidget_6.item(1)
        item.setText(_translate("userHomeMain", "     Role, Programming Languages Used, etc."))
        item = self.listWidget_6.item(3)
        item.setText(_translate("userHomeMain", "User Profile B"))
        item = self.listWidget_6.item(4)
        item.setText(_translate("userHomeMain", "     Role, Programming Languages Used, etc."))
        item = self.listWidget_6.item(6)
        item.setText(_translate("userHomeMain", "User Profile C"))
        item = self.listWidget_6.item(7)
        item.setText(_translate("userHomeMain", "     Role, Programming Languages Used, etc."))
        item = self.listWidget_6.item(9)
        item.setText(_translate("userHomeMain", "User Profile D"))
        item = self.listWidget_6.item(10)
        item.setText(_translate("userHomeMain", "     Role, Programming Languages Used, etc."))
        self.listWidget_6.setSortingEnabled(__sortingEnabled)
        self.label_14.setText(_translate("userHomeMain", "Group Members"))
        self.pushButton_16.setText(_translate("userHomeMain", "Invite"))
        self.label_16.setText(_translate("userHomeMain", "Manage Group"))
        self.pushButton_17.setText(_translate("userHomeMain", "Meet Up Poll"))
        self.pushButton_18.setText(_translate("userHomeMain", "Group Closing Poll"))
        self.pushButton_19.setText(_translate("userHomeMain", "Write Complaint"))
        self.pushButton_20.setText(_translate("userHomeMain", "Write Compliment"))
        self.pushButton_21.setText(_translate("userHomeMain", "Kick Out Member Poll"))
        self.label_17.setText(_translate("userHomeMain", "Meetings"))
        self.label_18.setText(_translate("userHomeMain", "1:00pm - 2:00pm, April 16, 2020."))
        self.label_19.setText(_translate("userHomeMain", "3:00pm - 4:30pm, April 24, 2020."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groupManagementTab), _translate("userHomeMain", "Group Management"))
        self.label_13.setText(_translate("userHomeMain", "Account Approval"))
        self.pushButton_11.setText(_translate("userHomeMain", "Select All"))
        self.pushButton_12.setText(_translate("userHomeMain", "Reject"))
        self.pushButton_13.setText(_translate("userHomeMain", "Deselect All"))
        self.pushButton_14.setText(_translate("userHomeMain", " Accept"))
        self.textBrowser_7.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.checkBox_6.setText(_translate("userHomeMain", "Account B: applicant name"))
        self.checkBox_8.setText(_translate("userHomeMain", "Account A: applicant name"))
        self.textBrowser_9.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.textBrowser_8.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.checkBox_9.setText(_translate("userHomeMain", "Account C: applicant name"))
        self.label_20.setText(_translate("userHomeMain", "Compliments & Complaints"))
        self.label_21.setText(_translate("userHomeMain", "Assign VIPs to Group Evaluations"))
        self.textBrowser_10.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Compliment details</p></body></html>"))
        self.checkBox_7.setText(_translate("userHomeMain", "Complaint: Username"))
        self.checkBox_10.setText(_translate("userHomeMain", "Compliment: Username"))
        self.textBrowser_11.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Complaint details</p></body></html>"))
        self.textBrowser_12.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.checkBox_11.setText(_translate("userHomeMain", "Account C: applicant name"))
        self.textBrowser_13.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">group exit evaluations from group members</p></body></html>"))
        self.textBrowser_14.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">group exit evaluations from group members</p></body></html>"))
        self.textBrowser_15.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.checkBox_14.setText(_translate("userHomeMain", "Account C: applicant name"))
        self.label_23.setText(_translate("userHomeMain", "Group name 1"))
        self.label_24.setText(_translate("userHomeMain", "Group name 2"))
        self.pushButton_22.setText(_translate("userHomeMain", "Assign"))
        self.pushButton_23.setText(_translate("userHomeMain", "Assign"))
        self.pushButton_24.setText(_translate("userHomeMain", " Accept"))
        self.pushButton_25.setText(_translate("userHomeMain", "Reject"))
        self.label_83.setText(_translate("userHomeMain", "Group Member Complaints"))
        self.textBrowser_62.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Group name and complaint details</p></body></html>"))
        self.textBrowser_63.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Group name and complaint details</p></body></html>"))
        self.textBrowser_64.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.checkBox_48.setText(_translate("userHomeMain", "Account C: applicant name"))
        self.label_84.setText(_translate("userHomeMain", "Group member name"))
        self.label_85.setText(_translate("userHomeMain", "Group member name"))
        self.pushButton_95.setText(_translate("userHomeMain", "Kick Out"))
        self.pushButton_96.setText(_translate("userHomeMain", "Kick Out"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adminSUTab), _translate("userHomeMain", "Admin (SU)*"))
        self.textBrowser_16.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">group exit evaluations from group members</p></body></html>"))
        self.checkBox_15.setText(_translate("userHomeMain", "Group name 2"))
        self.checkBox_16.setText(_translate("userHomeMain", "Group name 1"))
        self.textBrowser_17.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">group exit evaluations from group members</p></body></html>"))
        self.textBrowser_18.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">group exit evaluations from group members</p></body></html>"))
        self.checkBox_17.setText(_translate("userHomeMain", "Group name 3"))
        self.textBrowser_35.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">group exit evaluations from group members</p></body></html>"))
        self.checkBox_31.setText(_translate("userHomeMain", "Group name 4"))
        self.label_22.setText(_translate("userHomeMain", "Group Evaluations"))
        self.pushButton_56.setText(_translate("userHomeMain", "Deselect All"))
        self.pushButton_57.setText(_translate("userHomeMain", "Select All"))
        self.pushButton_55.setText(_translate("userHomeMain", " Assign Score"))
        self.label_49.setText(_translate("userHomeMain", "User Score Change"))
        self.textBrowser_36.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Score change reasons</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_37.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Score change reasons</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_38.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">referral name and referral email</p></body></html>"))
        self.label_50.setText(_translate("userHomeMain", "User name 1"))
        self.label_51.setText(_translate("userHomeMain", "User name 2"))
        self.pushButton_58.setText(_translate("userHomeMain", "Assign"))
        self.pushButton_59.setText(_translate("userHomeMain", "Assign"))
        self.textBrowser_39.setHtml(_translate("userHomeMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Score change reasons</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_60.setText(_translate("userHomeMain", "Assign"))
        self.label_52.setText(_translate("userHomeMain", "User name 3"))
        self.label_81.setText(_translate("userHomeMain", "Democratic SU Management"))
        self.label_82.setText(_translate("userHomeMain", "SU name and contact info"))
        self.pushButton_94.setText(_translate("userHomeMain", "Vote for SU"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("userHomeMain", "Admin (VIP)*"))
        self.label_25.setText(_translate("userHomeMain", "Project Tracker"))
        self.label_53.setText(_translate("userHomeMain", "Project Hierarchy Tree"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("userHomeMain", "Project Management (Creative Feature)"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userHomeMain = QtWidgets.QMainWindow()
    ui = Ui_userHomeMain()
    ui.setupUi(userHomeMain)
    ui.hideTab()
    userHomeMain.show()
    sys.exit(app.exec_())
